"""initial migration

Revision ID: 6e81b051adb7
Revises: 86fb418f5755
Create Date: 2025-01-29 11:14:12.030491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e81b051adb7'
down_revision: Union[str, None] = '86fb418f5755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_role', 'user', type_='foreignkey')
    op.drop_column('user', 'roleid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('roleid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_role', 'user', 'role', ['roleid'], ['id'])
    # ### end Alembic commands ###
